# Generated by Django 5.0.4 on 2024-05-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FacultyView", "0002_alter_uniqueid_unique_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uniqueid",
            name="unique_id",
            field=models.CharField(
                default="ox1mf8wmG3f104FuZyHcxBWQyhQDmaB5", max_length=32
            ),
        ),
    ]
