# Generated by Django 5.0.4 on 2024-05-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FacultyView", "0004_alter_uniqueid_unique_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uniqueid",
            name="unique_id",
            field=models.CharField(
                default="sXlbN28hGXpEmciX1ZDiBMN2wCr8sl0L", max_length=32
            ),
        ),
    ]
